#cloud-config
# For more info on the format of this user-data file see the following links:
# https://discuss.hashicorp.com/t/wrong-indent-with-multiline-content-to-cloud-init-write-files-content-directives/35011/2
# https://developer.hashicorp.com/terraform/language/functions/templatefile#generating-json-or-yaml-from-a-template
users:
  - name: ${user}
    ssh-authorized-keys:
    - ${ssh_pubkey}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
   # etcd User is Required for Installing with CIS Profile Enabled
  - name: etcd
    gecos: System Account for Running etcd Service
    sudo: false
    system: true
yum_repos:
  rancher:
    name: Rancher RPMs
    baseurl: https://rpm.rancher.io/rancher/production/centos/9/noarch
    enabled: 1 
    gpgcheck: 1 
    gpgkey: https://rpm.rancher.io/public.key
packages:
- vim
- bash-completion
- jq
runcmd:
- sysctl -p /etc/sysctl.d/90-kubelet.conf
- sudo systemctl disable firewalld
- sudo systemctl stop firewalld
- mkdir -p /var/run/istio-cni && semanage fcontext -a -t container_file_t /var/run/istio-cni && restorecon -v /var/run/istio-cni


